'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface NavLink {
  name: string;
  href: string;
}

const navLinks: NavLink[] = [
  { name: 'Register', href: './register' },
  { name: 'Login', href: './login' },
  { name: 'Products', href: './products' },
];

const spacer = ' | ';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [page, setPage] = useState<string>('');
  const router = useRouter();

  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '1rem',
          }}
        >
          <div>
            <h2>Header</h2>
            <h2>
              Fast Navigation{' '}
              <input value={page} onChange={(e) => setPage(e.target.value)} />
              <button
                onClick={() => {
                  router.push(`/${page}`);
                }}
              >
                Go
              </button>
            </h2>
          </div>
          {navLinks.map((item, index) => {
            const isActive = pathname.startsWith(item.href);
            return (
              <Link
                key={index}
                href={item.href}
                className={isActive ? 'font-bold mr-4' : 'font-blue mr-4'}
              >
                {item.name}
                {spacer}
              </Link>
            );
          })}
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'gray',
            padding: '1rem',
          }}
        >
          <div>footer</div>
        </footer>
      </body>
    </html>
  );
}
